#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use ADR\Filesystem\Workspace;
use ADR\Command\CreateAdrCommand;

$app = new Application('Lightweight Architecture Decision Records Tools');

$app->add(new CreateAdrCommand(new Workspace()));
$app->run();